[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wg-toolkit"
version = "0.1.0"
description = "Personal toolkit of reusable utilities"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
data     = ["pandas","scipy", "engineering-notation"]
serial   = ["pyserial"]
plotting = ["plotly"]
all      = [
    "wg-toolkit[data]",
    "wg-toolkit[serial]",
    "wg-toolkit[plotting]",
]
dev = [
    "nbstripout",
    "pytest",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
